- more correct solution for the XrdClientAdmin.pm

diff --git a/src/XrdClient/Makefile.am b/src/XrdClient/Makefile.am
--- a/src/XrdClient/Makefile.am
+++ b/src/XrdClient/Makefile.am
@@ -142,14 +142,22 @@ clean-local:
 # suitable swig is available, we instead create it anew
 # This needs to be done outside the ENABLE_PERLINT clause, to get a working
 # "make dist" target
-
+SWIG_TARGETS = XrdClientAdmin_c_wrap.cc XrdClientAdmin.pm
 if REBUILD_SWIGFILE
-XrdClientAdmin_c_wrap.cc: XrdClientAdmin_c.hh
+# This creates both the .cc file and the .pm perl module
+$(SWIG_TARGETS): XrdClientAdmin_c.hh
 	echo Creating swig perl interface
 	$(SWIG) -perl -o $@ $(srcdir)/XrdClientAdmin_c.hh
 else
 XrdClientAdmin_c_wrap.cc: XrdClientAdmin_c_wrap.c
 	cp $(srcdir)/XrdClientAdmin_c_wrap.c XrdClientAdmin_c_wrap.cc
+XrdClientAdmin.pm:
+	@if test -e $(srcdir)/XrdClientAdmin.pm; then \
+           cp $(srcdir)/XrdClientAdmin.pm XrdClientAdmin.pm; \
+        else \
+           echo "ERROR: You lost distribution's original $@. Refetch it."; \
+           exit 1; \
+        fi         
 endif
 
 if ENABLE_PERLINT
@@ -160,7 +168,7 @@ libXrdClientAdmin_la_LIBADD = $(clientlibs)
 
 libXrdClientAdmin_la_CXXFLAGS = $(PERL_CCOPTS)
 install-exec-local: libXrdClientAdmin.la XrdClientAdmin.pm
-	$(INSTALL) -m 644 $(srcdir)/XrdClientAdmin.pm  $(DESTDIR)/$(libdir)/XrdClientAdmin.pm
+	$(INSTALL) -m 644 XrdClientAdmin.pm  $(DESTDIR)/$(libdir)/XrdClientAdmin.pm
 endif
 
 # we need to include the pregenerated swig file in the distribution
